# -*- coding: utf-8 -*-
"""Python programming_week3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GR2gaqfrLHLHvMvyC9Cw69sFj-RCec2U
"""

base = int(input("입력 진수 결정(2,8,10,16): "))
value = input("값 입력:")

num = int(value,base)

print("16진수 :", hex(num))
print("10진수:", num)
print("8진수 :", oct(num))
print("2진수 :", bin(num))