# -*- coding: utf-8 -*-
"""Python programming_week5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ZW_09QRXOVCg76bPYhq1lryAJdcv_8t
"""

i,k,guideLine = 0,0,""

for i in range(2,10) :
  guideLine = guideLine + "  # %2d단  "%i

print(guideLine)

for i in range(1,10):
  guideLine = ""
  for k in range(2,10):
    guideLine = guideLine + str("%2d X%2d =%2d"%(k,1,k*i))

  print(guideLine)

