# -*- coding: utf-8 -*-
"""파이썬프로그래밍 2주차 과제.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Cho000000/cyh/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D%202%EC%A3%BC%EC%B0%A8%20%EA%B3%BC%EC%A0%9C.ipynb
"""

# 1. inch TO cm

inch = float(input("인치 값을 입력하세요: "))
cm = inch * 2.54
print(inch, "인치는", cm, "cm 입니다.")

# 2. kg To pound

kg = float(input("킬로그램 값을 입력하세요: "))
pound = round(kg * 2.20462,2)
print(kg, "kg은", pound, "파운드 입니다.")

# 3. Circlecal

pi = 3.141592 #원주율

radius = float(input("원의 반지름을 입력하세요: "))
circumference = round(2 * pi * radius,2)  # 둘레
area = round(pi * radius ** 2,2)  # 넓이

print("반지름", radius, "의 원 둘레:", circumference)
print("반지름", radius, "의 원 넓이:", area)